# Generated by Django 4.2.11 on 2024-06-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userrole',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Developer', 'Developer'), ('Tester', 'Tester')], max_length=20),
        ),
    ]
