# Generated by Django 4.2.11 on 2024-06-09 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team_leader',
        ),
        migrations.AddField(
            model_name='project',
            name='project_leader',
            field=models.ForeignKey(blank=True, limit_choices_to={'userrole': 'Developer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_location',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_project_duration',
            field=models.PositiveIntegerField(help_text='Enter the estimated duration in days'),
        ),
    ]
