# Generated by Django 4.2.11 on 2024-06-10 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bug_name', models.CharField(max_length=255)),
                ('bug_description', models.TextField(max_length=1000)),
                ('selected_project', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
                ('bug_category', models.CharField(default='Others', max_length=100)),
                ('total_time_spend', models.PositiveIntegerField(help_text='Enter the time spend duration in days')),
                ('bug_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very high', 'Very High')], default='low', max_length=10)),
                ('cvss_score', models.PositiveIntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('tester', models.ForeignKey(blank=True, limit_choices_to={'userrole': 'Tester'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile')),
            ],
        ),
    ]
