# Generated by Django 4.2.11 on 2024-06-10 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='selected_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
