# Generated by Django 4.2.11 on 2024-06-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default2.png', upload_to='profile_pics/'),
        ),
    ]
