# Generated by Django 4.2.11 on 2024-06-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_notification_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.CharField(default='system', max_length=80),
        ),
    ]
